on:
  release:
    types: [published]
  workflow_dispatch:
  push:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: uv build
        run: uv build
